"""
Cross-language parity check for the feature pipeline.

Compares features.py against a fixture generated by the TypeScript implementation, so the
browser and Colab provably compute the same vectors.

Usage:
    npm test --workspace @signsphere/web     # regenerate fixtures/parity.json
    python check_parity.py                   # verify

Run BOTH after any change to features.ts or features.py. A silent divergence here means
your Colab accuracy number describes a model that does not exist in the app — which is the
kind of error that survives all the way into a report.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np

import features as F

FIXTURE = Path(__file__).parent / "fixtures" / "parity.json"

# Float32 round-trip through JSON, plus a different summation order in numpy, means exact
# equality is not the right bar. 1e-6 is far tighter than anything that could affect a model.
TOLERANCE = 1e-6


def fail(message: str) -> None:
    print(f"  FAIL  {message}")


def main() -> int:
    if not FIXTURE.exists():
        print(f"Fixture not found: {FIXTURE}")
        print("Generate it first:  npm test --workspace @signsphere/web")
        return 2

    fixture = json.loads(FIXTURE.read_text(encoding="utf-8"))
    failures = 0

    print(f"Parity check against {FIXTURE.name}")
    print(f"  python: {F.layout_summary()}")
    print(
        f"  ts:     FEATURE_VERSION={fixture['featureVersion']} "
        f"FRAME_DIM={fixture['frameDim']} WINDOW_FRAMES={fixture['windowFrames']} "
        f"WINDOW_DIM={fixture['windowDim']}"
    )

    # --- constants -----------------------------------------------------------
    for name, ours, theirs in [
        ("FEATURE_VERSION", F.FEATURE_VERSION, fixture["featureVersion"]),
        ("FRAME_DIM", F.FRAME_DIM, fixture["frameDim"]),
        ("WINDOW_FRAMES", F.WINDOW_FRAMES, fixture["windowFrames"]),
        ("WINDOW_DIM", F.WINDOW_DIM, fixture["windowDim"]),
    ]:
        if ours != theirs:
            fail(f"{name}: python={ours} ts={theirs}")
            failures += 1

    offsets = fixture["offsets"]
    for name, ours in [
        ("dominantPresent", F.OFFSET_DOMINANT_PRESENT),
        ("dominantHand", F.OFFSET_DOMINANT_HAND),
        ("nonDominantPresent", F.OFFSET_NON_DOMINANT_PRESENT),
        ("nonDominantHand", F.OFFSET_NON_DOMINANT_HAND),
        ("dominantAbs", F.OFFSET_DOMINANT_ABS),
        ("nonDominantAbs", F.OFFSET_NON_DOMINANT_ABS),
        ("interHandVector", F.OFFSET_INTER_HAND_VECTOR),
        ("interHandDistance", F.OFFSET_INTER_HAND_DISTANCE),
        ("pose", F.OFFSET_POSE),
    ]:
        if offsets.get(name) != ours:
            fail(f"offset {name}: python={ours} ts={offsets.get(name)}")
            failures += 1

    # --- encode_frame --------------------------------------------------------
    for case in fixture["cases"]:
        expected = np.array(case["expected"], dtype=np.float32)
        actual = F.encode_frame(case["dominant"], case["nonDominant"], case["pose"])

        if actual.shape != expected.shape:
            fail(f"{case['name']}: shape python={actual.shape} ts={expected.shape}")
            failures += 1
            continue

        diff = np.abs(actual - expected)
        worst = int(np.argmax(diff))
        if diff[worst] > TOLERANCE:
            fail(
                f"{case['name']}: max diff {diff[worst]:.3e} at index {worst} "
                f"(python={actual[worst]:.8f} ts={expected[worst]:.8f})"
            )
            failures += 1
        else:
            print(f"  ok    {case['name']}  (max diff {diff[worst]:.2e})")

    # --- resample_window index mapping --------------------------------------
    # This is where JS Math.round vs Python round() bites. If it fails here, features.py is
    # using round() somewhere instead of floor(x + 0.5).
    for entry in fixture["resample"]:
        n = entry["n"]
        frames = np.zeros((n, F.FRAME_DIM), dtype=np.float32)
        for i in range(n):
            frames[i, 0] = i
        out = F.resample_window(frames)
        actual = [float(out[i, 0]) for i in range(F.WINDOW_FRAMES)]
        if actual != [float(v) for v in entry["indices"]]:
            fail(f"resample n={n}: index mapping differs (JS Math.round vs Python round?)")
            print(f"        python={actual}")
            print(f"        ts    ={entry['indices']}")
            failures += 1
        else:
            print(f"  ok    resample n={n}")

    print()
    if failures:
        print(f"PARITY BROKEN: {failures} check(s) failed. Do not train until this passes.")
        return 1
    print("PARITY OK - features.py and features.ts agree.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
