"""
Feature extraction — Python mirror of apps/web/src/lib/features.ts.

============================== KEEP IN SYNC ==============================
This file must produce byte-identical vectors to features.ts. A mismatch between the two is
the single most common cause of "95% in Colab, useless in the browser".

Run `python check_parity.py` after ANY change to either file. It compares this module
against a fixture generated by the TypeScript implementation.
=========================================================================

Two JS/Python differences that matter and are handled explicitly below:
  1. Math.round in JS rounds .5 UP; Python's round() uses banker's rounding (.5 to even).
     resample_window uses floor(x + 0.5) to match JS.
  2. JS Float32Array truncates to float32 on write. We cast to float32 at the end for the
     same reason.
"""

from __future__ import annotations

import math
from typing import Sequence

import numpy as np

FEATURE_VERSION = 1

HAND_POINTS = 21
POSE_POINTS = 25
WINDOW_FRAMES = 32

WRIST = 0
MIDDLE_MCP = 9
LEFT_SHOULDER = 11
RIGHT_SHOULDER = 12

# Offsets mirror OFFSET in features.ts. check_parity.py asserts these against the fixture.
OFFSET_DOMINANT_PRESENT = 0
OFFSET_DOMINANT_HAND = 1
OFFSET_NON_DOMINANT_PRESENT = 64
OFFSET_NON_DOMINANT_HAND = 65
OFFSET_DOMINANT_ABS = 128
OFFSET_NON_DOMINANT_ABS = 131
OFFSET_INTER_HAND_VECTOR = 134
OFFSET_INTER_HAND_DISTANCE = 137
OFFSET_POSE = 138

FRAME_DIM = OFFSET_POSE + POSE_POINTS * 3  # 213
WINDOW_DIM = FRAME_DIM * WINDOW_FRAMES  # 6816

Point = Sequence[float]  # (x, y, z)


def _distance(a: Point, b: Point) -> float:
    return math.sqrt((a[0] - b[0]) ** 2 + (a[1] - b[1]) ** 2 + (a[2] - b[2]) ** 2)


def _normalize_hand(points: Sequence[Point], out: np.ndarray, offset: int) -> None:
    """Wrist-relative, scale-normalised hand: handshape invariant to position and distance."""
    if len(points) < HAND_POINTS:
        return
    wrist = points[WRIST]
    middle = points[MIDDLE_MCP]
    span = _distance(wrist, middle) or 1.0

    for i in range(HAND_POINTS):
        p = points[i]
        base = offset + i * 3
        out[base] = (p[0] - wrist[0]) / span
        out[base + 1] = (p[1] - wrist[1]) / span
        out[base + 2] = (p[2] - wrist[2]) / span


def _torso_frame(pose: Sequence[Point] | None):
    if pose is None or len(pose) <= RIGHT_SHOULDER:
        return None
    left = pose[LEFT_SHOULDER]
    right = pose[RIGHT_SHOULDER]
    centre = (
        (left[0] + right[0]) / 2,
        (left[1] + right[1]) / 2,
        (left[2] + right[2]) / 2,
    )
    scale = _distance(left, right) or 1.0
    return centre, scale


def encode_frame(
    dominant: Sequence[Point] | None,
    non_dominant: Sequence[Point] | None,
    pose: Sequence[Point] | None,
) -> np.ndarray:
    """Encode one frame into FRAME_DIM float32 values. Mirrors encodeFrame() in features.ts."""
    out = np.zeros(FRAME_DIM, dtype=np.float64)
    torso = _torso_frame(pose)

    if dominant is not None:
        out[OFFSET_DOMINANT_PRESENT] = 1.0
        _normalize_hand(dominant, out, OFFSET_DOMINANT_HAND)
    if non_dominant is not None:
        out[OFFSET_NON_DOMINANT_PRESENT] = 1.0
        _normalize_hand(non_dominant, out, OFFSET_NON_DOMINANT_HAND)

    if torso is not None:
        centre, scale = torso
        if dominant is not None:
            w = dominant[WRIST]
            out[OFFSET_DOMINANT_ABS] = (w[0] - centre[0]) / scale
            out[OFFSET_DOMINANT_ABS + 1] = (w[1] - centre[1]) / scale
            out[OFFSET_DOMINANT_ABS + 2] = (w[2] - centre[2]) / scale
        if non_dominant is not None:
            w = non_dominant[WRIST]
            out[OFFSET_NON_DOMINANT_ABS] = (w[0] - centre[0]) / scale
            out[OFFSET_NON_DOMINANT_ABS + 1] = (w[1] - centre[1]) / scale
            out[OFFSET_NON_DOMINANT_ABS + 2] = (w[2] - centre[2]) / scale

        if pose is not None:
            for i in range(min(POSE_POINTS, len(pose))):
                p = pose[i]
                base = OFFSET_POSE + i * 3
                out[base] = (p[0] - centre[0]) / scale
                out[base + 1] = (p[1] - centre[1]) / scale
                out[base + 2] = (p[2] - centre[2]) / scale

    # Inter-hand geometry: contact and relative placement carry meaning in two-handed signs,
    # which are far more common in ISL than in ASL.
    if dominant is not None and non_dominant is not None:
        a = dominant[WRIST]
        b = non_dominant[WRIST]
        scale = torso[1] if torso is not None else 1.0
        out[OFFSET_INTER_HAND_VECTOR] = (a[0] - b[0]) / scale
        out[OFFSET_INTER_HAND_VECTOR + 1] = (a[1] - b[1]) / scale
        out[OFFSET_INTER_HAND_VECTOR + 2] = (a[2] - b[2]) / scale
        out[OFFSET_INTER_HAND_DISTANCE] = _distance(a, b) / scale

    return out.astype(np.float32)


def resample_window(frames: np.ndarray, target: int = WINDOW_FRAMES) -> np.ndarray:
    """
    Resample (n_frames, FRAME_DIM) to (target, FRAME_DIM) by nearest-neighbour index
    sampling. Nearest-neighbour, not interpolation: averaging two distinct handshapes
    produces a handshape that never occurred.
    """
    out = np.zeros((target, FRAME_DIM), dtype=np.float32)
    n = len(frames)
    if n == 0:
        return out

    for i in range(target):
        if n == 1:
            source = 0
        else:
            # floor(x + 0.5) matches JS Math.round; Python's round() does not.
            source = min(n - 1, int(math.floor(i * (n - 1) / (target - 1) + 0.5)))
        out[i] = frames[source]
    return out


def l2_normalize(vector: np.ndarray) -> np.ndarray:
    norm = float(np.linalg.norm(vector)) or 1.0
    return (vector / norm).astype(np.float32)


def layout_summary() -> str:
    return (
        f"FEATURE_VERSION={FEATURE_VERSION} FRAME_DIM={FRAME_DIM} "
        f"WINDOW_FRAMES={WINDOW_FRAMES} WINDOW_DIM={WINDOW_DIM}"
    )


if __name__ == "__main__":
    print(layout_summary())
